// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jahkeup/repost/notification (interfaces: SQSReceiver)

// Package notification is a generated GoMock package.
package notification

import (
	sqs "github.com/aws/aws-sdk-go/service/sqs"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSQSReceiver is a mock of SQSReceiver interface
type MockSQSReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockSQSReceiverMockRecorder
}

// MockSQSReceiverMockRecorder is the mock recorder for MockSQSReceiver
type MockSQSReceiverMockRecorder struct {
	mock *MockSQSReceiver
}

// NewMockSQSReceiver creates a new mock instance
func NewMockSQSReceiver(ctrl *gomock.Controller) *MockSQSReceiver {
	mock := &MockSQSReceiver{ctrl: ctrl}
	mock.recorder = &MockSQSReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSQSReceiver) EXPECT() *MockSQSReceiverMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method
func (m *MockSQSReceiver) DeleteMessage(arg0 *sqs.DeleteMessageInput) (*sqs.DeleteMessageOutput, error) {
	ret := m.ctrl.Call(m, "DeleteMessage", arg0)
	ret0, _ := ret[0].(*sqs.DeleteMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessage indicates an expected call of DeleteMessage
func (mr *MockSQSReceiverMockRecorder) DeleteMessage(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockSQSReceiver)(nil).DeleteMessage), arg0)
}

// ReceiveMessage mocks base method
func (m *MockSQSReceiver) ReceiveMessage(arg0 *sqs.ReceiveMessageInput) (*sqs.ReceiveMessageOutput, error) {
	ret := m.ctrl.Call(m, "ReceiveMessage", arg0)
	ret0, _ := ret[0].(*sqs.ReceiveMessageOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveMessage indicates an expected call of ReceiveMessage
func (mr *MockSQSReceiverMockRecorder) ReceiveMessage(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockSQSReceiver)(nil).ReceiveMessage), arg0)
}
